name: "Deploy para hostgator"
on: 
    push:
        branches:
            - deploy-hostgator

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Install npm dependencies 
      run: npm install 

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "SECRET=${{ secrets.SECRET }}" >> .env
        echo "ACCESS_TOKEN_MERCADOPAGO=${{ secrets.ACCESS_TOKEN_MERCADOPAGO }}" >> .env
        echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
        echo "GERENCIADOR_URL=${{ secrets.GERENCIADOR_URL }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
  
    - name: Run prisma migrations
      run: npx prisma migrate deploy

    - name: Build project  
      run: npm run build --if-present


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"